### ISSUE TITLE
Reddit scraping not working + potential infinite fail loop

### ISSUE THREAD

**Issue by NeoHuncho** [MohamedBassem/hoarder-app#100] opened 2024-04-13 22:04 UTC
When **I enter a reddit link, the worker fails to scrape the website**. Other websites do work (I tried out Medium and Github which worked flawlessly)

_Logs from my worker container_

```
024-04-13T21:45:40.392Z info: [Crawler][2] Will crawl "https://www.reddit.com/r/developpeurs/comments/1bwv8dv/je_suis_pass%C3%A9_freelance_et_cela_est_en_train_de/" for link with id "ziwvqyyfndx2tudibaaxu41f"
2024-04-13T21:45:40.535Z info: [search][3] Completed successfully
2024-04-13T21:45:50.031Z info: [Crawler][2] Successfully navigated to "https://www.reddit.com/r/developpeurs/comments/1bwv8dv/je_suis_pass%C3%A9_freelance_et_cela_est_en_train_de/". Waiting for the page to load ...
2024-04-13T21:45:55.072Z info: [Crawler][2] Finished waiting for the page to load.
2024-04-13T21:46:40.378Z error: [Crawler][2] Crawling job failed: Error: Timed-out after 60 secs
2024-04-13T21:46:41.434Z info: [Crawler][2] Will crawl "https://www.reddit.com/r/developpeurs/comments/1bwv8dv/je_suis_pass%C3%A9_freelance_et_cela_est_en_train_de/" for link with id "ziwvqyyfndx2tudibaaxu41f"
2024-04-13T21:46:49.728Z info: [Crawler][2] Successfully navigated to "https://www.reddit.com/r/developpeurs/comments/1bwv8dv/je_suis_pass%C3%A9_freelance_et_cela_est_en_train_de/". Waiting for the page to load ...
2024-04-13T21:46:54.729Z info: [Crawler][2] Finished waiting for the page to load.
2024-04-13T21:47:41.436Z error: [Crawler][2] Crawling job failed: Error: Timed-out after 60 secs
```

**This fail loop continued going until I stopped the container.** 

**Additional info:**
- I am using the latest release tag
- the containers are running on my raspberry pi 

Thanks for the amazing work :)

**Comment by MohamedBassem** [comment] 2024-04-13 22:07
> This fail loop continued going until I stopped the container.

This is the retries. A failed link will be retried 5 times and then get aborted. So don't worry, it's not "infinite".

As for the failed scraping, this seems to be a duplicate of https://github.com/MohamedBassem/hoarder-app/issues/93

**Comment by MohamedBassem** [comment] 2024-04-14 09:59
I'm going to close this in favor of #93

**Closed by MohamedBassem** 2024-04-14 09:59 UTC
