### ISSUE TITLE
Feature request: ARM64 / aarch64 version

### ISSUE THREAD

**Issue by helmut72** [MohamedBassem/hoarder-app#42] opened 2024-03-29 07:41 UTC
Would be cool to let it run on a Raspberry. Thanks.

**Comment by MohamedBassem** [comment] 2024-03-29 10:15
Thanks for opening this issue. I'm happy to build an aarch64 based image for hoarder. The problem is that some of the deps (chrome and meilisearch) don't have an ARM version. We can maybe use this issue to try to convince them to have aarch64 images as well.

**Comment by helmut72** [comment] 2024-03-29 10:34
Thanks for your answer.

Meilisearch does have an aarch64/arm64 version:
https://hub.docker.com/r/getmeili/meilisearch/tags

Same for Chrome:
https://hub.docker.com/r/zenika/alpine-chrome/tags

**Comment by MohamedBassem** [comment] 2024-03-29 10:36
Oh, if you're looking for `linux/arm64` then I'm publishing those as well. That's what the macOS uses in the new chips.

<img width="781" alt="Screenshot 2024-03-29 at 10 35 17 AM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/4e0aa254-ac55-481f-8c9b-0d3b004a7e40">

**Comment by lbrame** [comment] 2024-03-31 17:57
I have been trying to run this container on `arm64` as well. So far, I have observed two things:

1. The headless `chrome` container in use does not have a `linux/amd64` candidate for tag 100 (the one that is currently being used in the Dockerfile), but I have had success with getting it to run on ARM by changing from tag 100 to tag 102 in `docker-compose.yml`. 102 is the earliest tag on the linked registry that offers a `linux/arm64` artifact. I have briefly tested this change on my Intel laptop as well to make sure it doesn't break everything, and so far it seems to be working fine.
2. Although GitHub packages for both `hoarder-web` and `hoarder-workers` offer a `linux/arm64` artifact in the latest version, I have had no success getting them to work: I get `exec /usr/local/bin/docker-entrypoint.sh: exec format error` for both containers. Specifically linking the `linux/arm64` image link from ghcr and specifying `platform: linux/arm64` in the docker-compose file (any combination of these two steps) does not produce positive results.

For further diagnostics info, this is happening on a Raspberry Pi 4 Model B Rev 1.5 (4 GB), Raspberry Pi OS Lite based on Debian 12 (Bookworm), Docker version 25.0.4, build 1a576c5.

(Also, thanks for building this app! I've been trying it briefly on a amd64 box and it's lovely.)

**Comment by MohamedBassem** [comment] 2024-03-31 18:09
@lbrame thanks for the detailed investigation! I actually just noticed that I'm using an old chrome version in the docker compose. I should probably fix that.

As for the RPI, it's on my todo list to get hoarder to work on there. Will report back.

**Comment by MohamedBassem** [comment] 2024-04-06 13:09
Ok. Good news, I managed to find the problem that was preventing hoarder from running on RPI (fixed in https://github.com/MohamedBassem/hoarder-app/commit/e0bb1fc17e2fafc3950d964af976859323fc9ed6). Sorry it took so long!

Here's hoarder running on my RPI 4 :)

<img width="1286" alt="Screenshot 2024-04-06 at 2 07 42 PM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/bf98fe1d-280f-4eaa-bc15-3637dda0b385">


Only restriction is that you'll need to be running the 64-bit OS. 32-bit OSes are not supported.

This is going to be available in the next release. Or if you can't wait, the `latest` tag already has the fix!

**Closed by MohamedBassem** 2024-04-06 13:09 UTC
Labels: feature request

**Comment by helmut72** [comment] 2024-04-07 20:48
Thank you :)
